# Generated by Django 3.2.4 on 2021-06-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSM25UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.UUIDField(unique=True, verbose_name='UUID теста')),
                ('answer', models.CharField(max_length=1, verbose_name='Текст ответа')),
            ],
        ),
    ]
