# Generated by Django 3.2.4 on 2021-06-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_tests', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='fio',
            field=models.CharField(blank=True, max_length=500, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='group_code',
            field=models.CharField(blank=True, max_length=500, verbose_name='Код группы'),
        ),
    ]
