# Generated by Django 3.2.4 on 2021-06-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychological_tests', '0002_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='test_id',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер вопроса'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.PositiveBigIntegerField(choices=[(0, 'PSM25 test'), (1, 'Tailor test'), (2, 'Emotional Burnout test')], verbose_name='Тип теста')),
                ('finished', models.BooleanField(default=False, verbose_name='Попытка завершена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='useranswer',
            name='test_attempt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='psychological_tests.usertest', verbose_name='Запись теста'),
            preserve_default=False,
        ),
    ]
