# Generated by Django 3.2.4 on 2021-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_tests', '0002_psm25useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm25useranswer',
            name='test_id',
            field=models.UUIDField(verbose_name='UUID теста'),
        ),
    ]
