# Generated by Django 3.2.4 on 2021-06-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_tests', '0003_alter_psm25useranswer_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm25useranswer',
            name='answer',
            field=models.IntegerField(default=0, verbose_name='Текст ответа'),
        ),
    ]
