# Generated by Django 3.2.4 on 2021-06-18 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_tests', '0003_auto_20210618_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='test_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID попытки теста'),
        ),
    ]
