# Generated by Django 3.2.4 on 2021-06-18 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_tests', '0004_usertest_test_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSM25TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='')),
                ('result_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID результата (совпадает с UUID теста)')),
            ],
        ),
    ]
