# Generated by Django 3.2.4 on 2021-06-19 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_tests', '0006_tailortestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm25testresult',
            name='result_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID результата (совпадает с UUID теста)'),
        ),
        migrations.AlterField(
            model_name='tailortestresult',
            name='result_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID результата (совпадает с UUID теста)'),
        ),
    ]
