# Generated by Django 3.2.4 on 2021-06-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_tests', '0007_auto_20210619_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalBurnoutResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traumatic_circumstance', models.PositiveIntegerField(verbose_name='Переживание психотравмирующих обстоятельств')),
                ('self_dissatisfaction', models.PositiveIntegerField(verbose_name='Неудовлетворенность собой')),
                ('caged', models.PositiveIntegerField(verbose_name='Загнанност в клетку')),
                ('depression', models.PositiveIntegerField(verbose_name='Тревога и депрессия')),
                ('inappropriate_response', models.PositiveIntegerField(verbose_name='Неадекватное избирательное эмоциональное реагирование')),
                ('emotional_disorientation', models.PositiveIntegerField(verbose_name='Эмоционально-нравственная дизориентация')),
                ('emotion_economy', models.PositiveIntegerField(verbose_name='Расширение сферы экономии эмоций')),
                ('professional_duties_reduction', models.PositiveIntegerField(verbose_name='Редукция сферы экономии эмоций')),
                ('emotional_deficit', models.PositiveIntegerField(verbose_name='Эмоциональный дефицит')),
                ('emotional_detachment', models.PositiveIntegerField(verbose_name='Эмоциональная отстраненность')),
                ('personal_detachment', models.PositiveIntegerField(verbose_name='Личная отстраненность (деперсонализация)')),
                ('psychosomatic_and_psychovegetative_disorders', models.PositiveIntegerField(verbose_name='Психосоматические и психовегетативные нарушения')),
            ],
        ),
    ]
